app = "fly-hello-laravel-db-replay"

[env]
APP_ENV = "production"
APP_URL = "https://fly-hello-laravel-db-replay.fly.dev"
DB_CONNECTION = "pgsql"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
PRIMARY_REGION = "scl"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 50
soft_limit = 25

[[services.http_checks]]
grace_period = "2s"
interval = 5000
method = "get"
path = "/"
protocol = "http"
restart_limit = 5
timeout = 2000
tls_skip_verify = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.ports]]
handlers = ["http"]
port = 80

[[services.tcp_checks]]
grace_period = "2s"
interval = 5000
timeout = 2000
